### ISSUE TITLE
"[Fatal Error] Load Limit Exceeded! You may want to modify the load limit in the Tokenizer.java

### ISSUE THREAD

**Issue by napsternxg** [shangjingbo1226/AutoPhrase#13]
I have edited the `Tokenizer.java` file with maximum value as `100000000` on the following line: 

https://github.com/shangjingbo1226/AutoPhrase/blob/5f49499eac6b4c2c0df681d9d450bebcb6c50fbe/tools/tokenizer/src/Tokenizer.java#L628

```
"[Fatal Error] Load Limit Exceeded! You may want to modify the load limit in the Tokenizer.java
```

But, I still continue to get this error. What is the load limit based on? 

My data has around `200,000,000` phrases.

**Comment by shangjingbo1226** [comment]
You can try to make it larger. The reason that I'm doing this instead of reading line by line is that Java's BufferedReader has some issue when dealing with too long lines. The only difference is that using the larger loadCount, the efficiency will be worse. This "mapping text back" step is very tricky since the raw input could be very noisy. I'm also not 100% sure about the correctness. If you have better solutions, please let me know. Thanks!

**Comment by napsternxg** [comment]
OK thanks a lot, this helps in understanding the output. I will try something, if it improves I will send a PR.

**Comment by shangjingbo1226** [comment]
Great! Thanks!
