### ISSUE TITLE
Applying trained segmentation model on different text

### ISSUE THREAD

**Issue by napsternxg** [shangjingbo1226/AutoPhrase#6]
Thanks a lot for making this code available. 

I have a particular use case. I wish to train the segmentation model using a large corpora to get the useful key phrases and then apply that same model to different data. Is there a way that can be done? Looking at the `phrasal_segmentation.sh` it appears that the code in it is completely unrelated to the one used in `auto_phrase.sh`. 

I do understand that running the code on the combination of the large data + my data is a possibility. But I am looking for a more efficient solution if it is available. 

Do the the two scripts share any information, either via the tmp folder or some other way. If all I am interested in is tagging of quality phrases in text should I run `auto_phrase.sh` followed by `phrasal_segmentation.sh` or only the latter one?

Finally, since your code uses parallel processing, do you maintain the order of the output values compared to the input values. E.g. if the input file specified in `TEXT_TO_SEG` has sentences in some order will the output file  `segmentation.txt` have outputs in the same order ? 

Finally, is there a way to have the segmentation functions available as a library, which I can call on my text data?

**Comment by shangjingbo1226** [comment]
Thanks for your interests!

Yes, they share some information. The easiest solution is that, run the ```auto_phrase.sh``` first and ```phrasal_segmentation.sh``` second in the same directory. You can just specify two different raw text files in these two scripts.

More specially, the shared information is mainly the ```results/segmentation.model``` and some tokenizer's indexing files in the ```tmp``` folder (e.g., ```tmp/token_mapping.txt```).

About the parallel processing, yes, the order of the output values is the same as the input.

That's a good suggestion. However, since our tool relies on the tokenizer, it's a little hard to provide some end-to-end API for the sentence segmentation from the raw text. I will try if it's feasible.

Thanks!
Jingbo

**Comment by napsternxg** [comment]
@shangjingbo1226 thanks a lot for the feedback. I will try these out.

**Comment by djstrong** [comment]
I have trained a model on Wikipedia. I have `segmentation.model` and list of extracted phrases. How to apply this model to a new corpus to extract new phrases? Is it possible?
