### ISSUE TITLE
Mine phrase containing capital letters through AutoPhrase

### ISSUE THREAD

**Issue by YaoXinZhi** [shangjingbo1226/AutoPhrase#86]
The phrase mined by AutoPhrase have high quality, but we noticed that all phrases mined by AutoPhrase are lowercase, but some phrases that contain capital letters are equally important, such as "UV-A senstivity"--a sensitivity to ultraviolet light--. I want to know if it is possible to mine phrase that contain capital letters through AutoPhrase ?

**Comment by haibin-chen** [comment]
The reason is Tokenizer lowercase the word by default. You can modify the compile settings in [https://github.com/shangjingbo1226/AutoPhrase/blob/36312aea661c2d83ffa0f8a8d258f92de17b44c7/tools/tokenizer/readme(tokenizer).txt#L7](url), and recompile to Tokenizer.  
However, the default domain-specific knowledge bases (data/EN/wiki_quality.txt) are all lowercase, which may lead to the poor quality of mining phrases.
